### ISSUE TITLE
Sample for getAccessibilityNodeProvider()?

### ISSUE THREAD

**Issue by daisy1754** [googlesamples/android-BasicAccessibility#1]
http://developer.android.com/guide/topics/ui/accessibility/apps.html#virtual-hierarchy

> In order to provide a virtual view hierarchy for a view, override the getAccessibilityNodeProvider() method in your custom view or view group and return an implementation of AccessibilityNodeProvider. For an example implementation of this accessibility feature, see AccessibilityNodeProviderActivity in the ApiDemos sample project.

It seems this project is an only one that demonstrate usage of accessibility APIs, but it doesn't seem containing anything related getAccessibilityNodeProvider()? Where can I find official sample for getAccessibilityNodeProvider()? Do you plan to update this project?

**Comment by farmazon3000** [comment]
this is helpful https://github.com/appium/android-apidemos/blob/master/src/io/appium/android/apis/accessibility/AccessibilityNodeProviderActivity.java

**Comment by davidleeflippin** [comment]
**05***#

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
