### ISSUE TITLE
minSdkVersion 11 cannot be smaller than version 14

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [googlesamples/android-BasicAccessibility#4]
Error:Execution failed for task ':Application:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 11 cannot be smaller than version 14 declared in library [com.android.support:gridlayout-v7:26.1.0]

Possible solution update gradle mudule to 
defaultConfig {
        minSdkVersion 14
....}

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
