### ISSUE TITLE
Add repo description and website

### ISSUE THREAD

**Issue by dandv** [googlesamples/android-BasicAccessibility#5]
@shailen: https://github.com/googlesamples/android-BasicAccessibility shows "No description, website, or topics provided."

**Comment by Kericom** [comment]
http://kericontosoonmicrosoftappleicomtripled.business.site

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
