### ISSUE TITLE
Ignored Android SDK Build Tools version

### ISSUE THREAD

**Issue by dandv** [googlesamples/android-BasicAccessibility#7]
Getting this warning while building:

> Warning:The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by DANISAbbasi** [comment]
Samsung galaxy S7 edge need all settings thanks

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
